#!/source/this/sh
cd ..
poet.baptize $PWD/bin/bl.monty ~/.local/bin/bl.monty

export_ () { export $1=$2; }
export_ BLESSED_MONTY       $PWD
export_ BLESSED_MONTY_BIN   $PWD/bin
export_ BLESSED_MONTY_DST   $PWD/.build/monty

[ -d $BLESSED_MONTY_DST ] || {
    git clone  \
        https://github.com/magicmonty/bash-git-prompt \
        ${BLESSED_MONTY_DST}
}

.bl.monty () { . blessed.monty.src $* ; }
